import {useEffect,useState} from 'react';
import type {ActionRecord,DesktopAPI} from '../shared/types';
import {Modal,errorText} from './Dialogs';
type Activity={routes?:{seq:number;botId:string;reason:string;skillIds:string;createdAt:string;inputHash:string}[];recovery?:boolean;actions:ActionRecord[];events:{seq:number;kind:string;actionId:string;createdAt:string}[]};
export function ActivityPanel({invoke,onClose}:{invoke:DesktopAPI['invoke'];onClose:()=>void}){
 const [data,setData]=useState<Activity>({actions:[],events:[]}),[error,setError]=useState(''),[checked,setChecked]=useState<string[]>([]);
 useEffect(()=>{let live=true;const refresh=()=>void invoke<Activity>('activity.get').then(value=>{if(live)setData(value);}).catch(e=>{if(live)setError(errorText(e));});refresh();const timer=setInterval(refresh,2000);return()=>{live=false;clearInterval(timer);};},[invoke]);
 async function reconcile(id:string){try{await invoke('activity.reconcile',{id});setData(await invoke<Activity>('activity.get'));}catch(e){setError(errorText(e));}}
 return <Modal title="Activity" onClose={onClose} wide><div className="dialog-form"><p>Interrupted actions are never automatically replayed. Check the external result before marking an uncertain action reconciled, then resume the chat explicitly.</p>{error&&<p role="alert" className="error">{error}</p>}{data.recovery&&<p role="status">State restored from backup; the damaged snapshot was preserved in app data.</p>}<details><summary>Routing decisions</summary>{data.routes?.map(route=><p key={route.seq}>{route.reason} · Bot {route.botId} · Skills {route.skillIds} · {new Date(route.createdAt).toLocaleString()}<br/>Input fingerprint: {route.inputHash}</p>)}</details><div style={{maxHeight:'55vh',overflow:'auto'}}>{data.actions.length===0?<p>No recorded actions yet.</p>:data.actions.map(action=><section key={action.id} className="settings-card"><strong>{action.effectClass} · {action.effectId}</strong><p>{action.state} · {new Date(action.createdAt).toLocaleString()}</p><small>Chat: {action.chatId} · Actor: {action.actorId}<br/>Action: {action.id}<br/>Target fingerprint: {action.targetHash}<br/>Arguments fingerprint: {action.argsHash}</small>{action.state==='uncertain'&&<><label><input type="checkbox" checked={checked.includes(action.id)} onChange={e=>setChecked(e.target.checked?[...checked,action.id]:checked.filter(id=>id!==action.id))}/> I checked the external result; resuming will not repeat it automatically.</label><button className="button" disabled={!checked.includes(action.id)} onClick={()=>void reconcile(action.id)}>Mark reconciled</button></>}</section>)}<details><summary>Recent audit events</summary>{data.events.map(event=><p key={event.seq}>{event.seq} · {event.kind} · {new Date(event.createdAt).toLocaleString()}</p>)}</details></div></div></Modal>;
}
