import {useEffect, useRef, useState} from 'react';
import {LoaderCircle, RotateCcw, Upload, WandSparkles, X} from 'lucide-react';
import type {AppState, Bot, DesktopAPI, MediaModel} from '../shared/types';
import {avatarAccessories, avatarColors, avatarShapes} from '../shared/identity';
import {Avatar} from './Avatar';
import {errorText} from './Dialogs';

export function AvatarEditor({bot,state,invoke,onClose}:{bot:Bot;state:AppState;invoke:DesktopAPI['invoke'];onClose:()=>void}) {
 const [tab,setTab]=useState('bot'),[error,setError]=useState(''),[busy,setBusy]=useState(''),[preview,setPreview]=useState('');
 const connections=state.settings.connections.filter(c=>['openrouter','openai'].includes(c.provider));
 const [connection,setConnection]=useState(connections[0]?.id??''),[models,setModels]=useState<MediaModel[]>([]),[model,setModel]=useState(''),[prompt,setPrompt]=useState('');
 const request=useRef(''),live=useRef(true);
 useEffect(()=>{live.current=true;return()=>{live.current=false;if(request.current)void invoke('media.cancel',{requestId:request.current});};},[invoke]);
 async function act(task:string,work:()=>Promise<unknown>){setBusy(task);setError('');try{await work();}catch(e){if(live.current)setError(errorText(e));}finally{if(live.current)setBusy('');}}
 function patch(values:Record<string,unknown>){void act('save',()=>invoke('bot.update',{id:bot.id,...values}));}
 async function loadModels(){const id=crypto.randomUUID();request.current=id;await act('models',async()=>{const result=await invoke<{models:MediaModel[]}>('media.models',{requestId:id,connectionId:connection,purpose:'image'});if(live.current){setModels(result.models);setModel(result.models[0]?.id??'');}});}
 async function generate(){const id=crypto.randomUUID();request.current=id;await act('generate',async()=>{const result=await invoke<{image:string}>('media.generate',{requestId:id,connectionId:connection,model,prompt});if(live.current)setPreview(result.image);});}
 return <section className="avatar-editor" aria-label={`${bot.name}'s appearance`}><header><strong>A little personality</strong><button className="icon-button" aria-label="Close appearance editor" onClick={onClose}><X size={16}/></button></header><div className="avatar-editor-preview"><Avatar bot={preview?{...bot,avatarImage:preview}:bot} size={82} quiet/><span>{preview?'Preview your new look':bot.name}<small>Built into your bot.</small></span></div><nav className="appearance-tabs" aria-label="Appearance options">{['bot','cosmetics','upload','generate'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav>
 {error&&<p role="alert" className="options-error">{error}</p>}
 {tab==='bot'&&<><div className="shape-choices">{avatarShapes.map(shape=><button key={shape.id} aria-label={`Shape ${shape.name}`} aria-pressed={bot.avatar===shape.id&&!bot.avatarImage} disabled={!!busy} onClick={()=>patch({avatar:shape.id,avatarImage:''})}><Avatar bot={{...bot,avatar:shape.id,avatarImage:undefined,accessory:'none'}} size={34} quiet/><small>{shape.name}</small></button>)}</div><div className="color-choices" aria-label="Bot colors">{avatarColors.map(color=><button key={color} style={{background:color}} aria-label={`Color ${color}`} aria-pressed={bot.color===color} disabled={!!busy} onClick={()=>patch({color})}/>)}</div></>}
 {tab==='cosmetics'&&<div className="accessory-choices">{avatarAccessories.map(item=><button key={item.id} aria-label={item.name} aria-pressed={(bot.accessory??'none')===item.id} disabled={!!busy} onClick={()=>patch({accessory:item.id})}><Avatar bot={{...bot,accessory:item.id}} size={39} quiet/><span>{item.name}</span></button>)}</div>}
 {tab==='upload'&&<div className="appearance-upload"><p>Choose a photo or a character. We’ll fit it to your bot.</p><button className="panels-button" disabled={!!busy} onClick={()=>void act('upload',async()=>{const result=await invoke<{image:string}|null>('avatar.pick');if(result&&live.current)setPreview(result.image);})}><Upload size={15}/>Browse image</button><small>PNG, JPG or WebP · up to 10 MB</small></div>}
 {tab==='generate'&&<div className="appearance-generate">{connections.length?<><label>Connection<select value={connection} disabled={!!busy} onChange={e=>{setConnection(e.target.value);setModels([]);setModel('');}}>{connections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="panels-button" disabled={!!busy||!connection} onClick={()=>void loadModels()}>{busy==='models'?<LoaderCircle size={14} className="spin"/>:<WandSparkles size={14}/>}Load image models</button><label>Image model{models.length?<select aria-label="Image model" value={model} onChange={e=>setModel(e.target.value)}>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>:<input aria-label="Image model" value={model} onChange={e=>setModel(e.target.value)} placeholder="Exact model ID from your provider"/>}</label><label>Your character<textarea rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="A tiny sage-green explorer with curious eyes…" maxLength={4000}/></label><button className="panels-button panels-primary" disabled={!!busy||!model||!prompt.trim()} onClick={()=>void generate()}>{busy==='generate'?<LoaderCircle size={14} className="spin"/>:<WandSparkles size={14}/>} {busy==='generate'?'Creating…':'Generate avatar'}</button><small>Uses your provider’s image credits. Preview before applying.</small></>:<p>Add an OpenRouter or OpenAI connection in Settings → Models to generate an avatar.</p>}</div>}
 {preview&&<div className="avatar-preview-actions"><button className="panels-button" disabled={!!busy} onClick={()=>{patch({avatarImage:preview});setPreview('');}}>Use this avatar</button><button className="panels-text-button" onClick={()=>setPreview('')}>Discard</button></div>}
 <footer><button className="panels-text-button" disabled={!!busy} onClick={()=>{setPreview('');patch({resetAppearance:true});}}><RotateCcw size={13}/>Reset appearance</button>{busy&&<button className="panels-text-button" onClick={()=>void invoke('media.cancel',{requestId:request.current})}>Cancel request</button>}</footer></section>;
}
