import {useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import {X,LoaderCircle} from 'lucide-react';
import type {AppState,AvatarShape,Bot,Routine,DesktopAPI} from '../shared/types';
import {Avatar} from './Avatar';
import {mainBot} from '../shared/bots';
export const errorText=(error:unknown)=>error instanceof Error?error.message.replace(/^Error invoking remote method '[^']+': (Error: )?/,''):String(error);
export function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:ReactNode;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null;const frame=ref.current;frame?.querySelector<HTMLElement>('input,textarea,button,select')?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'&&frame){const nodes=Array.from(frame.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),a[href]')).filter(x=>x.offsetParent!==null);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);prior?.focus();};},[onClose]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div className={'modal '+(wide?'modal-wide':'')} ref={ref} role="dialog" aria-modal="true" aria-label={title}><header className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></header>{children}</div></div>;
}
export function BotDialog({bot,invoke,onClose,onCreated}:{bot?:Bot;invoke:DesktopAPI['invoke'];onClose:()=>void;onCreated?:(bot:Bot)=>void}){
 const [name,setName]=useState(bot?.name??'');const[role,setRole]=useState(bot?.role??'');const[instructions,setInstructions]=useState(bot?.instructions??'');const[memory,setMemory]=useState(bot?.memory??'');const[color,setColor]=useState(bot?.color??'#a99bef');const[avatar,setAvatar]=useState<AvatarShape>(bot?.avatar??'bloom');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 const preview={accessory:bot?.accessory,avatarImage:bot?.avatarImage,name:name||'New bot',avatar,color,status:'idle' as const};
 async function save(){setBusy(true);setError('');try{const saved=await invoke<Bot>(bot?'bot.update':'bot.create',{...(bot?{id:bot.id}:{}),name,role,instructions,memory,color,avatar});onCreated?.(saved);onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <Modal title={bot?'Bot settings':'Create a bot'} onClose={onClose}><form className="dialog-form" onSubmit={e=>{e.preventDefault();void save();}}><div className="bot-identity-form"><Avatar bot={preview} size={58}/><label>Name<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)} placeholder="A name for your bot"/></label></div><label>Role<input required maxLength={160} value={role} onChange={e=>setRole(e.target.value)} placeholder="What does this bot do?"/></label><label>Instructions<textarea rows={5} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Responsibilities, preferred methods, and what good work looks like."/></label>{bot&&<label>Remembered instructions<textarea rows={3} value={memory} onChange={e=>setMemory(e.target.value)} placeholder="Standing preferences for this bot"/></label>}<div className="form-row"><label>Appearance<select value={avatar} onChange={e=>setAvatar(e.target.value as AvatarShape)}><option value="orbit">Orbit</option><option value="prism">Facet</option><option value="pebble">Drift</option><option value="bloom">Bloom</option><option value="capsule">Dash</option><option value="sprout">Sprig</option><option value="triangle">Peak</option><option value="drop">Dew</option></select></label><label>Color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div>{error&&<p className="error" role="alert">{error}</p>}<footer className="dialog-footer"><span className="muted">Its own memory. Its own Linux computer.</span><button className="button primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:null}{bot?'Save changes':'Create bot'}</button></footer></form></Modal>;
}
export function RoutineDialog({bot,routine,timezone,invoke,onClose}:{bot:Bot;routine?:Routine;timezone:string;invoke:DesktopAPI['invoke'];onClose:()=>void}){
 const[name,setName]=useState(routine?.name??'');const[prompt,setPrompt]=useState(routine?.prompt??'');const[time,setTime]=useState(routine?.time??'09:00');const[days,setDays]=useState(routine?.days??[1,2,3,4,5]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 async function save(){setBusy(true);setError('');try{await invoke('routine.save',{...(routine?{id:routine.id}:{}),botId:bot.id,name,prompt,time,days,timezone,enabled:routine?.enabled??true});onClose();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <Modal title={routine?'Edit routine':'Add a routine'} onClose={onClose}><form className="dialog-form" onSubmit={e=>{e.preventDefault();void save();}}><div className="inline-bot"><Avatar bot={bot} size={32}/><span>{bot.name}</span></div><label>Name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Morning research brief"/></label><label>What should the bot do?<textarea required rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the recurring outcome"/></label><label>Run at<input required type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><div className="weekday-picker" aria-label="Days to run">{['S','M','T','W','T','F','S'].map((day,i)=><button key={i} type="button" aria-label={['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][i]} aria-pressed={days.includes(i)} onClick={()=>setDays(days.includes(i)?days.filter(d=>d!==i):[...days,i])}>{day}</button>)}</div><p className="muted">{timezone} · I Bot must be running for scheduled work.</p>{error&&<p className="error" role="alert">{error}</p>}<footer className="dialog-footer">{routine?<button type="button" className="button danger" onClick={async()=>{try{await invoke('routine.delete',{id:routine.id});onClose();}catch(e){setError(errorText(e));}}}>Delete routine</button>:<span/>}<button className="button primary" disabled={busy||!days.length}>{busy?'Saving…':'Save routine'}</button></footer></form></Modal>;
}
export function GroupDialog({state,invoke,onClose,onCreated}:{state:AppState;invoke:DesktopAPI['invoke'];onClose:()=>void;onCreated:(id:string)=>void}){
 const[name,setName]=useState('');const[selected,setSelected]=useState<string[]>([mainBot(state)?.id].filter((id):id is string=>!!id));const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 return <Modal title="Create group chat" onClose={onClose}><form className="dialog-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await invoke<{id:string}>('chat.create',{title:name||'New group',botIds:selected});onCreated(result.id);onClose();}catch(err){setError(errorText(err));}finally{setBusy(false);}}}><label>Group name<input value={name} onChange={e=>setName(e.target.value)} placeholder="A name for this conversation"/></label><div className="group-bots">{state.bots.map(bot=><label key={bot.id}><Avatar bot={bot} size={32}/><span>{bot.name}<small>{bot.role}</small></span><input type="checkbox" checked={selected.includes(bot.id)} onChange={()=>setSelected(selected.includes(bot.id)?selected.filter(id=>id!==bot.id):[...selected,bot.id])}/></label>)}</div>{error&&<p className="error">{error}</p>}<footer className="dialog-footer"><span className="muted">Chief can invite more bots as needed.</span><button className="button primary" disabled={busy||!selected.length}>Create group</button></footer></form></Modal>;
}
