import {useEffect,useState} from 'react';
import type {Bot,DesktopAPI} from '../shared/types';
import type {MemoryNote} from '../desktop/memory';
import {Modal,errorText} from './Dialogs';
export function MemoryPanel({bot,invoke,onClose}:{bot:Bot;invoke:DesktopAPI['invoke'];onClose:()=>void}){
 const[notes,setNotes]=useState<MemoryNote[]>([]),[selected,setSelected]=useState<MemoryNote|null>(null),[topic,setTopic]=useState(''),[content,setContent]=useState(''),[error,setError]=useState(''),[history,setHistory]=useState<MemoryNote[]>([]);
 async function refresh(){setNotes(await invoke<MemoryNote[]>('memory.list',{botId:bot.id}));}
 useEffect(()=>{void refresh().catch(e=>setError(errorText(e)));},[bot.id]);
 function choose(note:MemoryNote|null){setSelected(note);setTopic(note?.topic??'');setContent(note?.content??'');setHistory([]);setError('');}
 async function save(){try{await invoke('memory.save',{botId:bot.id,id:selected?.id,scope:selected?.scope??'bot',topic,content});await refresh();choose(null);}catch(e){setError(errorText(e));}}
 return <Modal title={`${bot.name}’s memory notes`} onClose={onClose} wide><div className="dialog-form"><p>Searchable Markdown notes with revision history. Notes guide the bot as reference data. Keep credentials and one-time codes out of memory.</p>{error&&<p className="error" role="alert">{error}</p>}<select aria-label="Select memory note" value={selected?.id??''} onChange={e=>choose(notes.find(note=>note.id===e.target.value)??null)}><option value="">New bot note</option>{notes.map(note=><option key={note.id} value={note.id}>{note.topic} · {note.scope} · {note.origin}</option>)}</select><label>Topic<input value={topic} maxLength={100} onChange={e=>setTopic(e.target.value)}/></label><label>Memory note<textarea rows={7} value={content} onChange={e=>setContent(e.target.value)}/></label>{selected&&<><small>{selected.path}</small><button className="button" onClick={async()=>{try{setHistory(await invoke<MemoryNote[]>('memory.revisions',{id:selected.id}));}catch(e){setError(errorText(e));}}}>Show revisions</button>{history.map((note,index)=><details key={index}><summary>{note.validFrom} · {note.origin}</summary><pre style={{whiteSpace:'pre-wrap'}}>{note.content}</pre><button className="button" onClick={async()=>{try{await invoke('memory.rollback',{id:selected.id,index});await refresh();choose(null);}catch(e){setError(errorText(e));}}}>Restore revision {index+1}</button></details>)}</>}<footer className="dialog-footer">{selected&&<button className="button danger" onClick={async()=>{try{await invoke('memory.delete',{id:selected.id});await refresh();choose(null);}catch(e){setError(errorText(e));}}}>Delete note and revisions</button>}<button className="button primary" disabled={!topic.trim()||!content.trim()} onClick={()=>void save()}>Save memory note</button></footer></div></Modal>;
}
