export interface CatalogApp {id:string;name:string;category:string;description:string;url:string;auth:'oauth'|'token';hint:string;docs:string;color:string;}
export const appCatalog:CatalogApp[]=[
 {id:'notion',name:'Notion',category:'Productivity',description:'Search, read, and work with your pages and databases.',url:'https://mcp.notion.com/mcp',auth:'oauth',hint:'Sign in and choose the Notion workspace you want your bots to use.',docs:'https://developers.notion.com/guides/mcp/get-started-with-mcp',color:'#ddd9cc'},
 {id:'linear',name:'Linear',category:'Productivity',description:'Keep issues, projects, and team work moving.',url:'https://mcp.linear.app/mcp',auth:'oauth',hint:'Authorize your Linear workspace in your browser. An API key is also supported.',docs:'https://linear.app/docs/mcp',color:'#a8a0dd'},
 {id:'github',name:'GitHub',category:'Development',description:'Explore repositories, issues, and pull requests.',url:'https://api.githubcopilot.com/mcp/',auth:'token',hint:'Use a GitHub personal access token with only the repository permissions you need.',docs:'https://github.com/github/github-mcp-server/blob/main/docs/remote-server.md',color:'#c6ced3'},
 {id:'sentry',name:'Sentry',category:'Development',description:'Investigate errors and performance in your applications.',url:'https://mcp.sentry.dev/mcp',auth:'oauth',hint:'Sign in to Sentry and authorize the organizations you want to connect.',docs:'https://mcp.sentry.dev/',color:'#c5a9bb'},
 {id:'cloudflare',name:'Cloudflare',category:'Development',description:'Manage infrastructure through Cloudflare’s official tools.',url:'https://mcp.cloudflare.com/mcp',auth:'oauth',hint:'Authorize your Cloudflare account. Account permissions determine available actions.',docs:'https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/',color:'#e8b478'},
 {id:'cloudflare-docs',name:'Cloudflare Docs',category:'Research',description:'Find official platform documentation without an account.',url:'https://docs.mcp.cloudflare.com/mcp',auth:'token',hint:'This documentation server is public. Leave the token empty.',docs:'https://developers.cloudflare.com/agents/model-context-protocol/cloudflare/servers-for-cloudflare/',color:'#e8b478'},
 {id:'apify',name:'Apify',category:'Research',description:'Search the web and run data collection tools.',url:'https://mcp.apify.com',auth:'oauth',hint:'Sign in to Apify or use an Apify API token. Actor runs can use your account credits.',docs:'https://docs.apify.com/integrations/mcp',color:'#91cba5'},
 {id:'huggingface',name:'Hugging Face',category:'Research',description:'Explore models, datasets, papers, and your chosen Spaces.',url:'https://huggingface.co/mcp',auth:'token',hint:'Copy the access token and endpoint from your Hugging Face MCP settings.',docs:'https://huggingface.co/settings/mcp',color:'#edcd7b'},
 {id:'stripe',name:'Stripe',category:'Finance',description:'Work with payments and business data in your Stripe account.',url:'https://mcp.stripe.com',auth:'oauth',hint:'Authorize Stripe in your browser, or supply a Stripe agent API key.',docs:'https://docs.stripe.com/mcp',color:'#acb0e9'},
];
