import { _electron as electron } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
const root=path.resolve('.');
const dataDir=await fs.mkdtemp(path.join(os.tmpdir(),'ibot-desktop-test-'));
await fs.mkdir(path.join(root,'artifacts','desktop'),{recursive:true});
const env={...process.env,IBOT_DATA_DIR:dataDir,IBOT_TEST:process.env.IBOT_RUNTIME_INTEGRATION==='1'?'0':'1'};
delete env.ELECTRON_RUN_AS_NODE;
let application;
const errors=[];
const launch=async()=>{application=await electron.launch({...(process.env.IBOT_TEST_EXECUTABLE?{executablePath:process.env.IBOT_TEST_EXECUTABLE,args:[]}:{args:[root]}),env,timeout:60000});const window=await application.firstWindow();window.setDefaultTimeout(30000);window.on('pageerror',error=>errors.push(error.message));await window.getByRole('textbox',{name:'Message your bot'}).waitFor({timeout:30000});return window;};
try{
 let page=await launch();
 const initial=await page.evaluate(()=>window.ibot.invoke('state.get'));
 assert.equal(initial.bots.length,1,'App starts with only Chief');
 assert.equal(initial.chats.length,0,'No simulated conversations');
 assert.equal(await page.getByRole('tab',{name:'Avatars',exact:true}).count(),0,'No separate avatar page');
 await page.screenshot({path:path.join(root,'artifacts','desktop','new-chat.png')});
 await page.getByRole('button',{name:'Create a bot',exact:true}).click();
 await page.locator('.messages').getByText("I'm ready to help. What would you like me to help you with?",{exact:true}).waitFor();
 assert.equal(await page.getByRole('dialog').count(),0,'Creation goes directly into conversation');
 assert.equal(await page.getByRole('button',{name:'Research a topic',exact:true}).count(),0,'No preset suggestion menu');
 await page.getByRole('button',{name:'Toggle bot details',exact:true}).click();await page.getByRole('button',{name:'Bot settings',exact:true}).click();
 await page.getByRole('textbox',{name:'Name',exact:true}).fill('Researcher');
 await page.getByRole('textbox',{name:'Role',exact:true}).fill('Research and verify sources');
 await page.getByRole('textbox',{name:'Instructions',exact:true}).fill('Collect evidence and cite sources.');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.getByRole('heading',{name:'Researcher',level:1,exact:true}).waitFor();
 let state=await page.evaluate(()=>window.ibot.invoke('state.get'));
 assert.equal(state.bots.length,2);
 const researcher=state.bots.find(bot=>bot.name==='Researcher');
 assert.ok(researcher);
 await page.getByRole('button',{name:'New chat',exact:true}).click();
 await page.getByRole('textbox',{name:'Message your bot'}).fill('Prepare a brief from these sources.');
 await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.getByRole('dialog').waitFor();
 assert.equal((await page.evaluate(()=>window.ibot.invoke('state.get'))).chats.length,1,'No extra chat or pretend run without a provider');
 await page.keyboard.press('Escape');
 await page.evaluate(()=>window.ibot.invoke('settings.update',{settings:{theme:'light',motion:'reduced'}}));
 await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
 await page.evaluate(()=>window.ibot.invoke('settings.update',{settings:{theme:'dark',motion:'full'}}));
 const created=await page.evaluate(async(botId)=>window.ibot.invoke('chat.create',{title:'Research collaboration',botIds:[(await window.ibot.invoke('state.get')).bots[0].id,botId]}),researcher.id);
 assert.ok(created.id);
 await page.getByRole('button',{name:/Research collaboration/}).click();
 await page.getByRole('heading',{name:'Research collaboration',exact:true}).waitFor();
 await page.screenshot({path:path.join(root,'artifacts','desktop','team-conversation.png')});
 await page.getByRole('button',{name:'Bot settings',exact:true}).click();
 await page.getByRole('textbox',{name:'Remembered instructions'}).fill('Prefer concise briefings with sources.');
 await page.getByRole('button',{name:'Save changes'}).click();
 await page.waitForFunction(()=>document.body.textContent.includes('Prefer concise briefings with sources.'));
 await application.close();application=null;
 page=await launch();
 state=await page.evaluate(()=>window.ibot.invoke('state.get'));
 assert.equal(state.bots.length,2,'Bots persist after restart');
 assert.equal(state.chats.length,2,'Onboarding and team chats persist after restart');
 assert.equal(state.bots[0].memory,'Prefer concise briefings with sources.');
 const vault=await application.evaluate(({safeStorage})=>{if(!safeStorage.isEncryptionAvailable())return false;const fixture='ibot-synthetic-vault-probe';const encrypted=safeStorage.encryptString(fixture);return safeStorage.decryptString(encrypted)===fixture&&!encrypted.toString().includes(fixture);});
 assert(vault,'Windows safeStorage must encrypt and decrypt a synthetic test value');
 await page.getByRole('button',{name:'Memory notes',exact:true}).click();
 await page.getByRole('textbox',{name:'Topic',exact:true}).fill('Travel');await page.getByRole('textbox',{name:'Memory note',exact:true}).fill('Prefer trains');await page.getByRole('button',{name:'Save memory note',exact:true}).click();
 await page.getByRole('combobox',{name:'Select memory note'}).selectOption({label:'Travel · bot · user'});
 await page.getByRole('textbox',{name:'Memory note',exact:true}).fill('Prefer ferries');await page.getByRole('button',{name:'Save memory note',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('select[aria-label="Select memory note"]')?.value==='');
 await page.getByRole('combobox',{name:'Select memory note'}).selectOption({label:'Travel · bot · user'});await page.getByRole('button',{name:'Show revisions'}).click();
 await page.locator('details').filter({has:page.getByText('Prefer trains',{exact:true})}).locator('summary').click();await page.getByRole('button',{name:'Restore revision 1'}).click();
 await page.waitForFunction(()=>document.querySelector('select[aria-label="Select memory note"]')?.value==='');
 await page.getByRole('combobox',{name:'Select memory note'}).selectOption({label:'Travel · bot · user'});assert.equal(await page.getByRole('textbox',{name:'Memory note',exact:true}).inputValue(),'Prefer trains');
 await page.getByRole('button',{name:'Delete note and revisions'}).click();await page.waitForFunction(()=>document.querySelector('select[aria-label="Select memory note"]')?.options.length===1);await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 assert.equal((await page.evaluate(()=>window.ibot.invoke('memory.list',{botId:'chief'}))).length,0);
 await page.getByRole('button',{name:/Ramesh.*Local profile/}).click();await page.getByRole('button',{name:'Activity',exact:true}).click();await page.getByRole('heading',{name:'Activity',exact:true}).waitFor();await page.getByText('Interrupted actions are never automatically replayed.',{exact:false}).waitFor();await page.getByRole('button',{name:'Close dialog',exact:true}).click();
 if(process.env.IBOT_RUNTIME_INTEGRATION==='1'){
   console.log('Checking Linux viewer');
   await page.getByRole('tab',{name:'Computer',exact:true}).click();
   await page.getByRole('button',{name:"Open Chief's computer",exact:true}).click();
   await page.getByRole('button',{name:'Take control',exact:true}).waitFor({state:'visible',timeout:120000});
   let frame=page.frameLocator('iframe[title="Chief\'s Linux desktop"]');
   await frame.locator('#status.connected').waitFor({state:'attached',timeout:30000});
   await page.screenshot({path:path.join(root,'artifacts','desktop','linux-computer.png')});
   console.log('Linux viewer connected; checking terminal');
   await page.locator('.computer-view').getByRole('button',{name:'Terminal',exact:true}).click();
   await page.getByRole('textbox',{name:'Terminal command'}).fill("printf 'desktop terminal verified' > /workspace/desktop-check.txt; cat /workspace/desktop-check.txt");
   await page.getByRole('button',{name:'Run command',exact:true}).click();
   await page.getByText('desktop terminal verified',{exact:true}).waitFor({timeout:30000});
   await page.locator('.computer-view').getByRole('button',{name:'Files',exact:true}).click();
   await page.getByRole('button',{name:'desktop-check.txt',exact:true}).click();
   await page.waitForFunction(()=>document.querySelector('textarea[aria-label="desktop-check.txt"]')?.value==='desktop terminal verified');
   assert.equal(await page.getByRole('textbox',{name:'desktop-check.txt'}).inputValue(),'desktop terminal verified');
   console.log('Files verified; checking teaching');
   await page.getByRole('button',{name:'Teach a task',exact:true}).click();
   await page.getByRole('textbox',{name:'Skill name'}).fill('Desktop workflow check');
   await page.getByRole('textbox',{name:'Instructions',exact:true}).fill('Check the report and save the verified output.');
   await page.getByRole('button',{name:'Start demonstration',exact:true}).click();
   frame=page.frameLocator('iframe[title="Chief\'s Linux desktop"]');
   await page.waitForFunction(()=>document.querySelector('iframe')?.src.includes('teach=true'));
   await frame.locator('#status.connected').waitFor({state:'attached',timeout:30000});
   await frame.locator('#screen canvas').click({position:{x:30,y:30}});
   await page.getByText('1 pointer and navigation steps captured.',{exact:false}).waitFor();
   await page.getByRole('button',{name:'Stop demonstration',exact:true}).click();
   await page.getByRole('button',{name:'Save skill',exact:true}).click();
   await page.getByRole('button',{name:'Skill saved',exact:true}).waitFor({timeout:30000});
   state=await page.evaluate(()=>window.ibot.invoke('state.get'));
   assert(state.skills.some(skill=>skill.name==='Desktop workflow check'&&skill.source==='taught'&&skill.botIds.includes('chief')));
   await page.evaluate(()=>window.ibot.invoke('workspace.stop',{botId:'chief'}));
 }
 assert.equal(errors.length,0,errors.join('\n'));
 console.log(JSON.stringify({passed:true,checks:['desktop boot','empty real state','inbuilt avatars','create bot','provider setup gate','theme and motion','group chat','memory','restart persistence','Windows safeStorage','Markdown notes edit/rollback/delete','Activity view',...(process.env.IBOT_RUNTIME_INTEGRATION==='1'?['Linux screen connection','Linux terminal','workspace file editor','demonstrated clicks','save taught skill']:[])],dataDir,screenshots:'artifacts/desktop'},null,2));
} finally {if(application){if(process.env.IBOT_RUNTIME_INTEGRATION==='1'){const page=await application.firstWindow();await page.evaluate(()=>window.ibot.invoke('workspace.stop',{botId:'chief'})).catch(()=>{});}await application.close();}}
